<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>netstandard2.1</TargetFramework>
	</PropertyGroup>

	<ItemGroup>
		<None Remove="Root\DockerRegistry\Docker.js" />
		<None Remove="Root\DockerRegistry\DockerOrganization.md" />
		<None Remove="Root\DockerRegistry\DockerOrganizations.md" />
		<None Remove="Root\DockerRegistry\DockerRepository.md" />
		<None Remove="Root\DockerRegistry\DockerStorage.md" />
		<None Remove="Root\DockerRegistry\DockerUser.md" />
		<None Remove="Root\DockerRegistry\DockerUsers.md" />
		<None Remove="Root\DockerRegistry\Repositories.md" />
		<None Remove="Root\DockerRegistry\Settings.md" />
		<None Remove="Root\DockerRegistry\Sniffers\Sniffer.md" />
		<None Remove="Root\DockerRegistry\Sniffers\StorageSniffer.js" />
		<None Remove="Root\DockerRegistry\Sniffers\StorageSniffer.md" />
		<None Remove="Root\DockerRegistry\Style.cssx" />
		<None Remove="TAG.Service.DockerRegistry.manifest" />
	</ItemGroup>

	<ItemGroup>
		<Content Include="Root\DockerRegistry\Docker.js">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
		<Content Include="Root\DockerRegistry\DockerOrganization.md">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
		<Content Include="Root\DockerRegistry\DockerOrganizations.md">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
		<Content Include="Root\DockerRegistry\DockerRepository.md">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
		<Content Include="Root\DockerRegistry\DockerStorage.md">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
		<Content Include="Root\DockerRegistry\DockerUser.md">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
		<Content Include="Root\DockerRegistry\DockerUsers.md">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
		<Content Include="Root\DockerRegistry\Repositories.md">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
		<Content Include="Root\DockerRegistry\Settings.md">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
		<Content Include="Root\DockerRegistry\Sniffers\Sniffer.md">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
		<Content Include="Root\DockerRegistry\Sniffers\StorageSniffer.js">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
		<Content Include="Root\DockerRegistry\Sniffers\StorageSniffer.md">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
		<Content Include="Root\DockerRegistry\Style.cssx">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
		<Content Include="TAG.Service.DockerRegistry.manifest">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Waher.IoTGateway" Version="3.8.1" />
		<PackageReference Include="Waher.Runtime.Timing" Version="2.1.1" />
		<PackageReference Include="Waher.Security" Version="1.3.0" />
		<PackageReference Include="Waher.Security.Users" Version="1.3.3" />
	</ItemGroup>

	<ItemGroup>
		<!-- TODO: ask if i should use package reference -->
		<ProjectReference Include="..\TAG.Networking.DockerRegistry\TAG.Networking.DockerRegistry.csproj" />
	</ItemGroup>

	<Target Name="PostBuild" AfterTargets="PostBuildEvent">
		<Exec Command="&quot;C:\My Projects\IoTGateway\Utilities\Waher.Utility.Install\bin\$(ConfigurationName)\net8.0\win-x86\Waher.Utility.Install.exe&quot; -m &quot;C:\My Projects\NeuronDockerRegistry\TAG.Service.DockerRegistry\bin\$(ConfigurationName)\netstandard2.1\TAG.Service.DockerRegistry.manifest&quot; -s &quot;C:\My Projects\IoTGateway\Waher.IoTGateway.Console\bin\$(ConfigurationName)\net8.0\Waher.IoTGateway.Console.dll&quot; -d &quot;C:\ProgramData\IoT Gateway Dev&quot;&#xD;&#xA;" />
	</Target>
</Project>
